In [1]:
import pandas as pd
from scipy.stats import friedmanchisquare
import scikit_posthocs as sp
import numpy as np
from matplotlib import cm, colors
import scipy.stats as ss
import pandas as pd

def underline_max(series):
    """Underline the maximum value(s) in a column."""
    is_max = series == series.max()        # Boolean Series
    return ['text-decoration: underline' if v else '' for v in is_max]

def underline_min(series):
    """Underline the maximum value(s) in a column."""
    is_min = series == series.min()        # Boolean Series
    return ['text-decoration: underline' if v else '' for v in is_min]

def print_pivot_to_latex(pivot_table):
    vmins = pivot_table.min()
    vmaxs = pivot_table.max()

    # --- Lighten the colormap (avoid overly dark greens)
    cmap = cm.get_cmap('Greens')
    def lighten_color_map(val):
        r, g, b, _ = val
        return (0.3 + 0.7 * r, 0.3 + 0.7 * g, 0.3 + 0.7 * b, 1)  # move toward lighter shades

    # --- Find max indices per column for underlining
    max_indices = pivot_table.idxmax()

    def color_cell(val, col):
        # normalize within column
        norm = colors.Normalize(vmin=vmins[col], vmax=vmaxs[col])
        r, g, b, _ = lighten_color_map(cmap(norm(val)))
        cell = f"\\cellcolor[rgb]{{{r:.3f},{g:.3f},{b:.3f}}}{val:.3f}"
        # underline max value per column
        if pivot_table.loc[:, col].idxmax() == idx:
            cell = f"\\underline{{{cell}}}"
        return cell

    # --- Build LaTeX table manually
    rows = []
    for idx, row in pivot_table.iterrows():
        colored = [color_cell(row[col], col) for col in pivot_table.columns]
        rows.append(f"{idx} & " + " & ".join(colored) + " \\\\")

    latex_table = (
        "\\begin{tabular}{l" + "r" * len(pivot_table.columns) + "}\n"
        + "Constraint & " + " & ".join(pivot_table.columns) + " \\\\\n"
        + "\\hline\n"
        + "\n".join(rows)
        + "\n\\end{tabular}"
    )

    print(latex_table)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 711, in start
    self.io_loop.start()
  File "/Us

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 711, in start
    self.io_loop.start()
  File "/Us

AttributeError: _ARRAY_API not found

In [12]:
import glob
import os
import pandas as pd
import scipy.stats as ss
from pathlib import Path

# -------------------------------------------------------
# 1. Load all CSVs into one big DataFrame
# -------------------------------------------------------
data_dir = Path(".")          # <-- change this
csv_paths = sorted(data_dir.glob("*.csv"))

dfs = []
for p in csv_paths:
    if 'suffix' in str(p) and 'not_local' in str(p):
        print(p)
        df = pd.read_csv(p)
#         print(df.head())
        # Keep the source dataset name (file stem)
        df["dataset"] = p.stem
        df = df[df.local == False]
        dfs.append(df)
        print(df['seed'].unique())
        
        for seed in df['seed'].unique():
            print(len(df[df['seed']==seed]))

df_all = pd.concat(dfs, ignore_index=True)

results_suffix_prediction_not_local_BPI12.csv
[  56    8   15   76   23    4   16   42  108 1089]
12
12
12
12
12
12
12
12
12
12
results_suffix_prediction_not_local_BPI17.csv
[1089   15   23   76   56    8]
12
12
12
12
12
12
results_suffix_prediction_not_local_BPI19.csv
[   4    8   15   16   23   42   56   76  108 1089]
11
12
22
11
11
11
12
11
11
11
results_suffix_prediction_not_local_BPI20PrepaidTravelCosts.csv
[  56    8   15   76   23   42    4  108   16 1089]
12
12
12
12
12
12
12
12
12
12
results_suffix_prediction_not_local_BPI20RequestForPayment.csv
[  56    8   15   76   23   42    4  108   16 1089]
12
12
12
12
12
12
12
12
12
12
results_suffix_prediction_not_local_BPI20TravelPermitData.csv
[  56    8   15   76   23    4   16   42  108 1089]
12
12
12
12
12
12
12
12
12
12


In [13]:
df_all

,seed,local,quantile,model,lambda,d_model,er_loss,batch_size,no_epochs,avg_dl_distance,time,er_pred,er_target,dataset
0,56,False,0.95,suffix_model,0.0,16,False,32,20,0.661030,43.777257,0.000000,0.000000,results_suffix_prediction_not_local_BPI12
1,56,False,0.95,suffix_model,0.0,32,False,32,20,0.649467,44.734853,0.000000,0.000000,results_suffix_prediction_not_local_BPI12
2,56,False,0.95,suffix_model,0.0,64,False,32,20,0.629988,45.055351,0.000000,0.000000,results_suffix_prediction_not_local_BPI12
3,56,False,0.95,SDFA_suffix_model,0.1,16,True,32,20,0.677929,46.177583,0.039038,0.038876,results_suffix_prediction_not_local_BPI12
4,56,False,0.95,SDFA_suffix_model,0.2,16,True,32,20,0.687892,45.278903,0.039012,0.038876,results_suffix_prediction_not_local_BPI12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,1089,False,0.95,SDFA_suffix_model,0.2,32,True,32,20,0.499371,29.865540,0.026748,0.026092,results_suffix_prediction_not_local_BPI20Trave...
671,1089,False,0.95,SDFA_suffix_model,0.5,32,True,32,20,0.507278,29.875395,0.026715,0.026092,results_suffix_prediction_not_local_BPI20Trave...
672,1089,False,0.95,SDFA_suffix_model,0.1,64,True,32,20,0.491322,29.902104,0.026868,0.026092,results_suffix_prediction_not_local_BPI20Trave...
673,1089,False,0.95,SDFA_suffix_model,0.2,64,True,32,20,0.489846,29.981536,0.026401,0.026092,results_suffix_prediction_not_local_BPI20Trave...


In [14]:
for p in csv_paths:
    if 'suffix' in str(p) and 'ns' not in str(p):
        print(p)
        
        df = pd.read_csv(p)
        # df = df[df['lambda']<0.5]
        df = df[df['local'] == False]

        df_test = df[['seed', 'model', 'd_model', 'avg_dl_distance']]

        df_test = (
            df_test
            .groupby(['seed', 'model'])
            .agg(f1_mean=('avg_dl_distance', 'max'))
            .reset_index()
        )

        sub = df_test
        pivot = sub.pivot(index='seed', columns='model', values='f1_mean')
        print(pivot)
        stat, p = ss.wilcoxon(pivot['SDFA_suffix_model']-pivot['suffix_model'])
        print(stat)
        print(p)


results_suffix_prediction_ND_BPI12.csv
model  SDFA_suffix_model  suffix_model
seed                                  
4               0.683486      0.670213
8               0.690063      0.673377
15              0.681935      0.666964
16              0.680316      0.654009
23              0.691476      0.665138
42              0.709288      0.662179
56              0.687892      0.661030
76              0.697517      0.675200
108             0.690244      0.690427
1089            0.711199      0.671523
1.0
0.00390625
results_suffix_prediction_ND_BPI17.csv
model  SDFA_suffix_model  suffix_model
seed                                  
8               0.633042      0.588213
56              0.621466      0.615953
1089            0.625907      0.595122
0.0
0.25
results_suffix_prediction_ND_BPI19.csv
model  SDFA_suffix_model  suffix_model
seed                                  
4               0.442413      0.426463
8               0.430508      0.432603
15              0.434930      0.433465
1

In [19]:
import glob
import os
import pandas as pd
import scipy.stats as ss
from pathlib import Path

# -------------------------------------------------------
# 1. Load all CSVs into one big DataFrame
# -------------------------------------------------------
data_dir = Path(".")          # <-- change this
csv_paths = sorted(data_dir.glob("*.csv"))

dfs = []
for p in csv_paths:
    if 'suffix' in str(p) and 'not_local' in str(p):
        df = pd.read_csv(p)
        # Keep the source dataset name (file stem)
        df["dataset"] = p.stem
        df['er_diff'] = (df['er_pred'] - df['er_target']) / (df['er_pred'])
        dfs.append(df)

df_all = pd.concat(dfs, ignore_index=True)

# -------------------------------------------------------
# 2. Basic filtering
# -------------------------------------------------------
# df_all = df_all[df_all["lambda"] < 0.5]
df_all = df_all[df_all['local'] == False]

# -------------------------------------------------------
# 3. Keep only the metrics we care about
# -------------------------------------------------------
cols_needed = ["dataset", "seed", "model", "d_model", "lambda", "avg_dl_distance", "er_diff"]
df_all = df_all[cols_needed]

# -------------------------------------------------------
# 4. Find the best parameter setting per seed–model–dataset
# -------------------------------------------------------
best = (
    df_all
    .sort_values("avg_dl_distance", ascending=False)          # highest f1 first
    .drop_duplicates(subset=["dataset", "seed", "model"], keep="first")
    .reset_index(drop=True)
)

# -------------------------------------------------------
# 5. Average metrics over seeds, grouped by dataset & model
# -------------------------------------------------------
summary = (
    best
    .groupby(["dataset", "model"], as_index=False)
    .agg(
        f1_mean=("avg_dl_distance", "mean"),
        precision_mean=("er_diff", "mean")
    )
)

# -------------------------------------------------------
# 6. Pivot so that each model becomes a column
# -------------------------------------------------------
pivot_f1 = summary.pivot(index="dataset", columns="model", values="f1_mean")
pivot_prec = summary.pivot(index="dataset", columns="model", values="precision_mean")

print(pivot_f1)

# -------------------------------------------------------
# 7. Statistical test per dataset
# -------------------------------------------------------
# 7a. Build a DataFrame with the two model columns side‑by‑side
model_a, model_b = sorted(df_all["model"].unique())  # ensure consistent order
tests = []

for ds in df_all["dataset"].unique():
    sub = best[best["dataset"] == ds]
#     if len(shared_seeds) < 3:   # Wilcoxon needs at least 3 pairs
#         continue
    vals_a = sub[sub["model"] == model_a].sort_values("seed")["avg_dl_distance"].values
    vals_b = sub[sub["model"] == model_b].sort_values("seed")["avg_dl_distance"].values
    stat, p = ss.wilcoxon(vals_a - vals_b)   # difference a – b
    tests.append({"dataset": ds,
                  "stat": stat,
                  "p": p,
                  f"{model_a}_mean": vals_a.mean(),
                  f"{model_b}_mean": vals_b.mean()})

tests_df = pd.DataFrame(tests)
pd.set_option("display.precision", 3)

# a) Merge the metric pivots with the test results
final_table = pivot_f1.copy()
print(final_table)
final_table.columns = [f"{c}_dl" for c in final_table.columns]
final_table = final_table.merge(
    pivot_prec.rename(columns={c: f"{c}_er" for c in pivot_prec.columns}),
    left_index=True, right_index=True
)
print(final_table)
# final_table = final_table.merge(tests_df[["dataset", "p"]], left_index=True, right_index=True)
final_table
# print(final_table)

model                                               SDFA_suffix_model  \
dataset                                                                 
results_suffix_prediction_not_local_BPI12                       0.692   
results_suffix_prediction_not_local_BPI17                       0.620   
results_suffix_prediction_not_local_BPI19                       0.435   
results_suffix_prediction_not_local_BPI20Prepai...              0.470   
results_suffix_prediction_not_local_BPI20Reques...              0.357   
results_suffix_prediction_not_local_BPI20Travel...              0.516   

model                                               suffix_model  
dataset                                                           
results_suffix_prediction_not_local_BPI12                  0.669  
results_suffix_prediction_not_local_BPI17                  0.599  
results_suffix_prediction_not_local_BPI19                  0.431  
results_suffix_prediction_not_local_BPI20Prepai...         0.403  
results_suffi

,SDFA_suffix_model_dl,suffix_model_dl,SDFA_suffix_model_er,suffix_model_er
dataset,,,,
results_suffix_prediction_not_local_BPI12,0.692,0.669,4.797e-03,NaN
results_suffix_prediction_not_local_BPI17,0.620,0.599,2.212e-03,NaN
results_suffix_prediction_not_local_BPI19,0.435,0.431,4.465e-02,NaN
results_suffix_prediction_not_local_BPI20PrepaidTravelCosts,0.470,0.403,5.302e-06,NaN
results_suffix_prediction_not_local_BPI20RequestForPayment,0.357,0.329,1.559e-02,NaN
results_suffix_prediction_not_local_BPI20TravelPermitData,0.516,0.497,2.147e-02,NaN


In [5]:
import pandas as pd
import numpy as np
from matplotlib import cm, colors

df = pd.read_csv('results_suffix_prediction_ND_BPI20PrepaidTravelCosts.csv')

pivot_table = pd.pivot_table(df, 
                             values=['avg_dl_distance'], 
                             
                             index=['local', 'batch_size', 'model', 'd_model', 'lambda'], 
                             aggfunc=np.mean)
styled_table = pivot_table.style.background_gradient(cmap='Blues').apply(underline_min, axis=0)
styled_table

/var/folders/rz/s0r_wmmx54b8t4zd9_r9xqbr0000gn/T/ipykernel_4792/465085709.py:7: FutureWarning: The provided callable <function mean at 0x1075da2a0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot_table = pd.pivot_table(df,


In [11]:
import pandas as pd
import numpy as np
from matplotlib import cm, colors

df = pd.read_csv('results_suffix_prediction_BPI20RequestForPayment.csv')

df = df[df['batch_size']<30]
pivot_table = pd.pivot_table(df, 
                             values=['avg_dl_distance'], 
                             
                             index=['local', 'batch_size', 'model', 'd_model', 'lambda'], 
                             aggfunc=np.mean)
styled_table = pivot_table.style.background_gradient(cmap='Blues').apply(underline_min, axis=0)
styled_table

/var/folders/rz/s0r_wmmx54b8t4zd9_r9xqbr0000gn/T/ipykernel_67180/948701201.py:8: FutureWarning: The provided callable <function mean at 0x1107c65c0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot_table = pd.pivot_table(df,


In [15]:
import pandas as pd
import numpy as np
from matplotlib import cm, colors

df = pd.read_csv('results_suffix_prediction_BPI12.csv')

df = df[df['batch_size']<30]
pivot_table = pd.pivot_table(df, 
                             values=['avg_dl_distance'], 
                             
                             index=['local', 'batch_size', 'model', 'd_model', 'lambda'], 
                             aggfunc=np.mean)
styled_table = pivot_table.style.background_gradient(cmap='Blues').apply(underline_min, axis=0)
styled_table

/var/folders/rz/s0r_wmmx54b8t4zd9_r9xqbr0000gn/T/ipykernel_67180/4148795791.py:8: FutureWarning: The provided callable <function mean at 0x1107c65c0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot_table = pd.pivot_table(df,
